version: "3.9"

services:
  stt-py:
    build:
      context: ./speech-to-text-service
      dockerfile: Dockerfile
    restart: always
    environment:
      - MQTT_URL=emqx
      - MQTT_PORT=1883
      - MQTT_TOPIC_SUB=voice-publish
      - MQTT_TOPIC_PUB=voice-consume
      - OPENAI_API_KEY=
    volumes:
      - tempfile:/app/temp
    networks:
      - sst-network-backend
    depends_on:
      - emqx

  emqx:
    image: emqx:5
    ports:
      - 1883:1883
      - 18083:18083
    networks:
      - sst-network-backend

  pocketbase:
    build:
      context: ./pocketbase
      dockerfile: Dockerfile
      args:
        - VERSION=0.13.4
    ports:
      - 8090:8090
    volumes:
      - ./pocketbase/pb_data:/pb_data
    networks:
      - sst-network-backend
      - sst-network-frontend

  speech-publisher:
    build:
      context: ./go-speech-publisher
      dockerfile: Dockerfile
      args:
        - APP_NAME=speechpublisher
        - APP_PORT=8080
    restart: always
    environment:
      - MQTT_HOST=emqx
      - MQTT_PORT=1883
      - USERNAME=
      - PASSWORD=

      # Gin server
      - PORT=8080

      # MQTT topics
      - MQTT_PUBLISH_TOPIC=voice-publish

    ports:
      - 8080:8080
    networks:
      - sst-network-backend
    volumes:
      - tempfile:/app/temp
    depends_on:
      - emqx
      - pocketbase

  speech-comsumer:
    build:
      context: ./go-speech-publisher
      dockerfile: Dockerfile
      args:
        - APP_NAME=speechconsumer
    restart: always
    networks:
      - sst-network-backend
    environment:
      - MQTT_HOST=emqx
      - MQTT_PORT=1883
      - USERNAME=
      - PASSWORD=

      - MQTT_SUBSCRIBE_TOPIC=voice-consume

      # Pocketbase Dashboard
      - POCKETBASE_PUBLISH_PROTOCOL=http
      - POCKETBASE_PUBLISH_HOST=pocketbase
      - POCKETBASE_PUBLISH_PORT=8090
      - POCKETBASE_PUBLISH_PATH=/api/collections/dashboard/records
    depends_on:
      - emqx
      - pocketbase

  frontend:
    build:
      context: ./next-frontend
      dockerfile: Dockerfile
    restart: always
    environment:
      # default env for frontend, if want to change it, please change it in .env file and build again
      - NEXT_PUBLIC_API_URL=http://localhost:8080/api/v1 # default api url for speech publisher
      - NEXT_PUBLIC_API_DB=http://localhost:8090 # default api url for pocketbase
    ports:
      - 3000:3000
    networks:
      - sst-network-frontend

networks:
  sst-network-frontend:
  sst-network-backend:

volumes:
  tempfile:
