version: "3"

services:
  stt-py:
    build: ./speech-to-text-service/Dockerfile
    volumes:
      - speech-to-text-service:/STT
    environment:
      - STT_SCORER_PATH=
      - STT_MODEL_PATH=
      - MQTT_URL=emqx
      - MQTT_PORT=1883
      - MQTT_TOPIC_SUB=
      - MQTT_TOPIC_PUB=
    entrypoint: [ "bin/sh", "start.sh" ]

  emqx:
    image: emqx:5
    ports:
      - 1883:1883
      - 18083:18083
