version: "3"

services:
  stt-py:
    build:
      context: ./speech-to-text-service
      dockerfile: Dockerfile
    environment:
      - STT_SCORER_PATH=large_vocabulary.scorer
      - STT_MODEL_PATH=model.tflite
      - MQTT_URL=emqx
      - MQTT_PORT=1883
      - MQTT_TOPIC_SUB=voice-publish
      - MQTT_TOPIC_PUB=voice-consume
    entrypoint: ["bin/sh", "start.sh"]

  emqx:
    image: emqx:5
    ports:
      - 1883:1883
      - 18083:18083

  pocketbase:
    build:
      context: ./pocketbase
      dockerfile: Dockerfile
      args:
        - VERSION=0.13.4
    ports:
      - 8090:8090

  speech-publisher:
    build:
      context: ./go-speech-publisher
      dockerfile: Dockerfile
      args:
        - APP_NAME=speechpublisher
        - APP_PORT=8080
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - emqx
      - pocketbase

  speech-comsumer:
    build:
      context: ./go-speech-publisher
      dockerfile: Dockerfile
      args:
        - APP_NAME=speechconsumer
    restart: always
    depends_on:
      - emqx
      - pocketbase

  frontend:
    build:
      context: ./next-frontend
      dockerfile: Dockerfile
    restart: always
    ports:
      - 3000:3000
