version: "3.9"

services:
  stt-py:
    image: dockerhub.warayut.xyz/microservice-cloud-app-stt-py
    restart: always
    environment:
      - STT_SCORER_PATH=./large_vocabulary.scorer
      - STT_MODEL_PATH=./model.tflite
      - MQTT_URL=emqx
      - MQTT_PORT=1883
      - MQTT_TOPIC_SUB=voice-publish
      - MQTT_TOPIC_PUB=voice-consume
    volumes:
      - ./speech-to-text-service:/STT
    networks:
      - sst-network
    depends_on:
      - emqx

  emqx:
    image: emqx:5
    ports:
      - 1883:1883
      - 18083:18083
    networks:
      - sst-network

  pocketbase:
    build:
      context: ./pocketbase
      dockerfile: Dockerfile
      args:
        - VERSION=0.13.4
    ports:
      - 8090:8090
    networks:
      - sst-network

  speech-publisher:
    build:
      context: ./go-speech-publisher
      dockerfile: Dockerfile
      args:
        - APP_NAME=speechpublisher
        - APP_PORT=8080
    restart: always
    environment:
      - MQTT_HOST=emqx
      - MQTT_PORT=1883
      - USERNAME=
      - PASSWORD=

      # Gin server
      - PORT=8080

      # MQTT topics
      - MQTT_PUBLISH_TOPIC=voice-publish

    ports:
      - 8080:8080
    networks:
      - sst-network
    depends_on:
      - emqx
      - pocketbase

  speech-comsumer:
    build:
      context: ./go-speech-publisher
      dockerfile: Dockerfile
      args:
        - APP_NAME=speechconsumer
    restart: always
    networks:
      - sst-network
    environment:
      - MQTT_HOST=emqx
      - MQTT_PORT=1883
      - USERNAME=
      - PASSWORD=

      # Pocketbase Dashboard
      - POCKETBASE_PUBLISH_PROTOCOL=http
      - POCKETBASE_PUBLISH_HOST=host.docker.internal
      - POCKETBASE_PUBLISH_PORT=8090
      - POCKETBASE_PUBLISH_PATH=/api/collections/dashboard/records
    depends_on:
      - emqx
      - pocketbase

  frontend:
    build:
      context: ./next-frontend
      dockerfile: Dockerfile
    restart: always
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8080/api/v1
      - NEXT_PUBLIC_API_DB=http://localhost:8090
    ports:
      - 3000:3000
    networks:
      - sst-network

networks:
  sst-network:
    driver: bridge
