name: CI Workflow microservice-cloud-app

on:
  push:
    branches:
      - main

jobs:

  build-next-frontend:
    uses: ./.github/workflows/docker-reusable-build.yaml
    with:
      image_name: rackz/next-frontend
      file: ./next-frontend/Dockerfile
    secrets:
      docker_username: ${{ secrets.DOCKER_USERNAME }}
      docker_password: ${{ secrets.DOCKER_PASSWORD }}

  build-speech-publisher:
    uses: ./.github/workflows/docker-reusable-build.yaml
    with:
      image_name: rackz/speech-publisher
      file: ./go-speech-publisher/Dockerfile
      build-arg: |
        APP_NAME=speechpublisher
        APP_PORT=8080
    secrets:
      docker_username: ${{ secrets.DOCKER_USERNAME }}
      docker_password: ${{ secrets.DOCKER_PASSWORD }}

  build-speech-consumer:
    uses: ./.github/workflows/docker-reusable-build.yaml
    with:
      image_name: rackz/speech-consumer
      file: ./go-speech-publisher/Dockerfile
      build-arg: |
        APP_NAME=speechconsumer
    secrets:
      docker_username: ${{ secrets.DOCKER_USERNAME }}
      docker_password: ${{ secrets.DOCKER_PASSWORD }}

  build-pocketbase:
    uses: ./.github/workflows/docker-reusable-build.yaml
    with:
      image_name: rackz/pocketbase
      file: ./pocketbase/Dockerfile
      build-arg: |
        VERSION=0.13.4
    secrets:
      docker_username: ${{ secrets.DOCKER_USERNAME }}
      docker_password: ${{ secrets.DOCKER_PASSWORD }}
